-- MySQL Script generated by MySQL Workbench
-- Sat Apr 12 21:18:46 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema Restaurante
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Restaurante
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Restaurante` DEFAULT CHARACTER SET utf8 ;
USE `Restaurante` ;

-- -----------------------------------------------------
-- Table `Restaurante`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante`.`cliente` (
  `ID_Cliente` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NULL,
  `Email` VARCHAR(200) NOT NULL,
  `Direccion` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`ID_Cliente`));


-- -----------------------------------------------------
-- Table `Restaurante`.`restaurante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante`.`restaurante` (
  `ID_Restaurante` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(200) NULL,
  `Ubicacion` VARCHAR(200) NOT NULL,
  `Telefono` VARCHAR(12) NULL,
  `Horario_atencion` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_Restaurante`));


-- -----------------------------------------------------
-- Table `Restaurante`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante`.`empleado` (
  `ID_Empleado` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(150) NULL,
  `Cargo` VARCHAR(90) NULL,
  `Telefono` VARCHAR(12) NULL,
  `Email` VARCHAR(150) NULL,
  `Fecha_contratacion` DATETIME NOT NULL,
  `ID_Restaurante` INT NOT NULL,
  PRIMARY KEY (`ID_Empleado`),
  CONSTRAINT `fk_empleado_restaurante1`
    FOREIGN KEY (`ID_Restaurante`)
    REFERENCES `Restaurante`.`restaurante` (`ID_Restaurante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Restaurante`.`mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante`.`mesa` (
  `ID_Mesa` INT NOT NULL AUTO_INCREMENT,
  `Numero` INT NOT NULL,
  `Capacidad` INT NOT NULL,
  `Estado` TINYINT NULL,
  `ID_Restaurante` INT NOT NULL,
  PRIMARY KEY (`ID_Mesa`),
  CONSTRAINT `fk_mesa_restaurante1`
    FOREIGN KEY (`ID_Restaurante`)
    REFERENCES `Restaurante`.`restaurante` (`ID_Restaurante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Restaurante`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante`.`pedido` (
  `ID_Pedido` INT NOT NULL AUTO_INCREMENT,
  `fecha` VARCHAR(45) NULL,
  `Hora` VARCHAR(45) NULL,
  `Estado` TINYINT NULL,
  `ID_Cliente` INT NOT NULL,
  `ID_Empleado` INT NOT NULL,
  `ID_Mesa` INT NOT NULL,
  PRIMARY KEY (`ID_Pedido`),
  CONSTRAINT `fk_pedido_cliente`
    FOREIGN KEY (`ID_Cliente`)
    REFERENCES `Restaurante`.`cliente` (`ID_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_empleado1`
    FOREIGN KEY (`ID_Empleado`)
    REFERENCES `Restaurante`.`empleado` (`ID_Empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_mesa1`
    FOREIGN KEY (`ID_Mesa`)
    REFERENCES `Restaurante`.`mesa` (`ID_Mesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Restaurante`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante`.`categoria` (
  `ID_Categoria` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(150) NULL,
  PRIMARY KEY (`ID_Categoria`));


-- -----------------------------------------------------
-- Table `Restaurante`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante`.`producto` (
  `ID_Producto` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(150) NOT NULL,
  `Descripcion` VARCHAR(150) NULL,
  `Precio` DOUBLE NULL,
  `ID_Categoria` INT NOT NULL,
  PRIMARY KEY (`ID_Producto`),
  CONSTRAINT `fk_producto_categoria1`
    FOREIGN KEY (`ID_Categoria`)
    REFERENCES `Restaurante`.`categoria` (`ID_Categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Restaurante`.`detalle_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante`.`detalle_pedido` (
  `ID_Detalle` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NULL,
  `Precio_total` DOUBLE NULL,
  `ID_Pedido` INT NOT NULL,
  `ID_Producto` INT NOT NULL,
  PRIMARY KEY (`ID_Detalle`),
  CONSTRAINT `fk_detalle_pedido_pedido1`
    FOREIGN KEY (`ID_Pedido`)
    REFERENCES `Restaurante`.`pedido` (`ID_Pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_pedido_producto1`
    FOREIGN KEY (`ID_Producto`)
    REFERENCES `Restaurante`.`producto` (`ID_Producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Restaurante`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurante`.`factura` (
  `ID_Factura` INT NOT NULL AUTO_INCREMENT,
  `Monto_total` DOUBLE NOT NULL,
  `Metodo_pago` VARCHAR(45) NULL,
  `Fecha_emision` DATETIME NULL,
  `ID_Pedido` INT NOT NULL,
  PRIMARY KEY (`ID_Factura`),
  CONSTRAINT `fk_factura_pedido1`
    FOREIGN KEY (`ID_Pedido`)
    REFERENCES `Restaurante`.`pedido` (`ID_Pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


